
apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: param-examples
description: toubleshoot params
inputs:
  p1:
    description: p1
    required: true
  p2:
    description: p2
    required: true
  p3:
    description: p3
    required: true
    default: "{}"
runs:
  using: composite
  steps:
    - id: process
      name: process the inputs
      uses: docker://gururepservice/curljq:latest
      shell: sh
      run: |
        #!/usr/bin/env bash
        printf "running tests\n"
        echo ${{ inputs.p1 }}
        echo ${{ inputs.p2 }}
        echo ${{ inputs.p3 }}
        jq --version
        PARAMETERS=${{ inputs.p3 }}
        BUILD_REQUEST=$(cat <<EOF
        {
          "buildType": {
            "id": "$BUILD_CONFIG_ID"
          },
          "branchName": "foobranch",
          "properties": {
            "property": $(echo "$PARAMETERS" | jq -r 'to_entries | map({name: .key, value: .value})')
          }
        }
        EOF
        )
        echo $BUILD_REQUEST
